"use client";
import { FormEvent,useEffect,useState } from "react";
import AppShell from "../components/AppShell";
import type { Dataset } from "../lib/types";
type Tab="pegawai"|"tujuan"|"rekening"|"pejabat";
const rupiah=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
export default function Master(){
  const [data,setData]=useState<Dataset|null>(null),[tab,setTab]=useState<Tab>("pegawai"),[error,setError]=useState(""),[success,setSuccess]=useState(""),[saving,setSaving]=useState(false);
  useEffect(()=>{let cancel=false;fetch("/api/sppd").then(async r=>{const j=await r.json() as Dataset&{error?:string};if(!r.ok)throw new Error(j.error||"Gagal memuat.");if(!cancel)setData(j)}).catch(e=>{if(!cancel)setError(e instanceof Error?e.message:"Gagal memuat.")});return()=>{cancel=true}},[]);
  async function submit(event:FormEvent<HTMLFormElement>,action:string){event.preventDefault();setSaving(true);setError("");setSuccess("");try{const payload=Object.fromEntries(new FormData(event.currentTarget).entries());const r=await fetch("/api/sppd",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,payload})});const j=await r.json() as Dataset&{error?:string};if(!r.ok)throw new Error(j.error||"Gagal menyimpan.");setData(j);setSuccess("Data berhasil disimpan.");event.currentTarget.reset()}catch(e){setError(e instanceof Error?e.message:"Gagal menyimpan.")}finally{setSaving(false)}}
  return <AppShell><div className="page-heading"><div><p className="eyebrow">Sumber data utama</p><h1>Master data</h1><p>Seluruh pilihan formulir dapat ditambah dan diisi manual.</p></div></div>
    {error?<div className="alert error">{error}</div>:null}{success?<div className="alert success">{success}</div>:null}
    <div className="tabs">{([["pegawai","Pegawai"],["tujuan","Tujuan & tarif"],["rekening","Kegiatan & rekening"],["pejabat","Pejabat"]] as Array<[Tab,string]>).map(([value,label])=><button key={value} className={tab===value?"active":""} onClick={()=>setTab(value)}>{label}</button>)}</div>
    <div className="master-grid"><section className="panel"><div className="panel-head"><div><p className="eyebrow">Daftar aktif</p><h2>{tab==="pegawai"?"Pegawai":tab==="tujuan"?"Tujuan perjalanan":tab==="rekening"?"Kegiatan dan rekening":"Pejabat penanda tangan"}</h2></div></div><div className="table-scroll">
      {tab==="pegawai"?<table className="data-table"><thead><tr><th>Nama / NIP</th><th>Jabatan</th><th>Pangkat</th><th>Uang harian</th></tr></thead><tbody>{data?.employees.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.nip}</small></td><td>{item.position}<small>{item.work_unit}</small></td><td>{item.rank}</td><td>{rupiah.format(item.daily_rate)}</td></tr>)}</tbody></table>:null}
      {tab==="tujuan"?<table className="data-table"><thead><tr><th>Tujuan</th><th>Jenis</th><th>Tarif transport</th></tr></thead><tbody>{data?.destinations.map(item=><tr key={item.id}><td>{item.name}</td><td>{item.trip_type==="luar"?"Luar daerah":"Dalam daerah"}</td><td>{rupiah.format(item.transport_rate)}</td></tr>)}</tbody></table>:null}
      {tab==="rekening"?<table className="data-table"><thead><tr><th>Kegiatan</th><th>Kode rekening</th></tr></thead><tbody>{data?.accounts.map(item=><tr key={item.id}><td>{item.activity_name}</td><td>{item.account_code}</td></tr>)}</tbody></table>:null}
      {tab==="pejabat"?<table className="data-table"><thead><tr><th>Jabatan / nama</th><th>Pangkat</th><th>NIP</th></tr></thead><tbody>{data?.signatories.map(item=><tr key={item.id}><td><strong>{item.role}</strong><small>{item.name}</small></td><td>{item.rank}</td><td>{item.nip}</td></tr>)}</tbody></table>:null}
    </div></section>
    {tab==="pegawai"?<form className="side-form" onSubmit={e=>void submit(e,"addEmployee")}><h2>Tambah pegawai</h2><p>Tarif menjadi nilai awal dan tetap bisa diubah.</p><label>Nama<input name="name" required/></label><label>NIP<input name="nip"/></label><label>Jabatan<input name="position"/></label><label>Pangkat / golongan<input name="rank"/></label><label>Unit kerja<input name="work_unit"/></label><label>Uang harian<input name="daily_rate" type="number"/></label><button className="button primary" disabled={saving}>Simpan pegawai</button></form>:null}
    {tab==="tujuan"?<form className="side-form" onSubmit={e=>void submit(e,"addDestination")}><h2>Tambah tujuan</h2><p>Tujuan dipisahkan menurut jenis perjalanan.</p><label>Nama tujuan<input name="name" required/></label><label>Jenis<select name="trip_type"><option value="dalam">Dalam daerah</option><option value="luar">Luar daerah</option></select></label><label>Tarif transport<input name="transport_rate" type="number"/></label><button className="button primary" disabled={saving}>Simpan tujuan</button></form>:null}
    {tab==="rekening"?<form className="side-form" onSubmit={e=>void submit(e,"addAccount")}><h2>Tambah kegiatan</h2><p>Dipakai pada pembebanan anggaran.</p><label>Uraian kegiatan<textarea name="activity_name" required/></label><label>Kode rekening<input name="account_code"/></label><button className="button primary" disabled={saving}>Simpan kegiatan</button></form>:null}
    {tab==="pejabat"?<form className="side-form" onSubmit={e=>void submit(e,"addSignatory")}><h2>Tambah pejabat</h2><p>Dapat dipilih sebagai penanda tangan.</p><label>Jabatan<input name="role"/></label><label>Nama<input name="name" required/></label><label>NIP<input name="nip"/></label><label>Pangkat<input name="rank"/></label><label>Wilayah pada tanda tangan<input name="region_line"/></label><button className="button primary" disabled={saving}>Simpan pejabat</button></form>:null}
    </div></AppShell>
}
